const number1 = 7;
const number2 = 4;
const product = number1 * number2;
console.log('value of product:', product);
console.log('typeof product:', typeof product);
const payment = 4.5;
const charge = 10;
const amountRemaining = charge - payment;
console.log('value of amountRemaining:', amountRemaining);
console.log('typeof amountRemaining:', typeof amountRemaining);
const tests = 80;
const assignments = 90;
const final = 100;
const grade = ((tests + assignments + final) / 3);
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
const firstName = 'Alex';
const lastName = 'Arce';
const fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
const pH = 15;
const isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
const numberOfSoldiers = 222;
const isSparta = numberOfSoldiers === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log('value of nickname:', nickname);
console.log('typeof nickname:', typeof nickname);
